random data for each file
OS-M/hsbench pull request #2
Opened 2023-10-31 16:58 UTC by d1tyo

2023-10-31 17:12 UTC, OS-M requested changes

2023-10-31 17:12 UTC, OS-M commented on hsbench.go
> +	return data
вообще я бы хотел что-то побыстрее стандартного рандома, но наверное пока можно так оставить. Если будет медленно, будем думать

2023-10-31 17:12 UTC, OS-M commented on hsbench.go
> +	return (int64(h.Sum64()) ^ it) * 1099511628211
1. разве безопасно переполнять int? Мне казалось, это уб
2. почему бы просто не записать в h.Write байты из it?

2023-10-31 17:12 UTC, OS-M commented on hsbench.go
> +		fileobj := bytes.NewReader(object_data[:objectLen])
а зачем генерить больше данных и потом их обрезать? Давай сразу в generateData передадим objectLen

2023-10-31 17:12 UTC, OS-M commented on hsbench.go
> +		ts_seed := time.Now().UnixMilli()
вообще в гошке переменные именуются camelCase'ом, но в hsbench что-то насрано как попало, поэтому можно так оставить для единообразия

2023-10-31 17:52 UTC, d1tyo commented on hsbench.go
> +		fileobj := bytes.NewReader(object_data[:objectLen])
Угу, смысла нет, убрал.

2023-10-31 18:00 UTC, d1tyo commented on hsbench.go
> +	return (int64(h.Sum64()) ^ it) * 1099511628211
1. В го - хз, в плюсах да, уб. Поправил, спасибо.
2. Я чот с ходу не нагуглил красивый способ. Только через encoding/binary. Если так делать канонично, ок, переделал. Так даже наверное правильнее будет, с точке зрения подсчёта хеша (т.к. мой изначальный вариант непобайтовый хак).

2023-10-31 18:05 UTC, d1tyo commented on hsbench.go
> +	return data
У меня были мысли просто прегенерированный массив шаффлить, чтоб арифметики на рандомной генерации избежать. Но тогда при достаточно малом сообщении будет мало возможных перестановок. Плюс набор символов в каждой сообщении при таком подходе был бы фиксированый.
В целом да, этот момент можно будет потом пробенчмаркать. Если перф устраивать не будет, то свою лёгкую формулу напишем.

2023-11-01 13:38 UTC, d1tyo commented on hsbench.go
> +func generateData(seed int64, len int) []byte {
Затащил RandomReadSeeker.

2023-11-01 21:48 UTC, d1tyo commented
добавил в это же ревью логирование инфы об объектах в файл

2023-11-13 17:48 UTC, OS-M approved these changes

2023-11-14 11:27 UTC, merged